import type { ExerciseSet, WordSearchExercise, PictogramCrosswordExercise } from "./types";

// Pre-generated Word Search Exercises (Sopa de Letras)
// All grids are 10x10 with words carefully placed to avoid overlaps and out-of-bounds

const wordSearchExercises: WordSearchExercise[] = [
  // Exercise 1: Animals
  {
    id: "ws-1",
    type: "word-search",
    title: "SOPA DE LETRAS - ANIMALES",
    instructions: "ENCUENTRA LAS PALABRAS DE ANIMALES ESCONDIDAS",
    gridSize: 10,
    words: ["GATO", "PERRO", "PATO", "RANA", "LEON"],
    wordPositions: [
      { word: "GATO", startRow: 0, startCol: 0, direction: "horizontal" },
      { word: "PERRO", startRow: 2, startCol: 1, direction: "horizontal" },
      { word: "PATO", startRow: 4, startCol: 5, direction: "vertical" },
      { word: "RANA", startRow: 6, startCol: 0, direction: "horizontal" },
      { word: "LEON", startRow: 1, startCol: 8, direction: "vertical" },
    ],
    grid: [
      ["G", "A", "T", "O", "X", "M", "K", "P", "Q", "R"],
      ["B", "C", "D", "E", "F", "H", "I", "J", "L", "S"],
      ["N", "P", "E", "R", "R", "O", "T", "U", "E", "V"],
      ["W", "Y", "Z", "A", "B", "C", "D", "E", "O", "F"],
      ["G", "H", "I", "J", "K", "P", "M", "N", "N", "O"],
      ["P", "Q", "R", "S", "T", "A", "V", "W", "X", "Y"],
      ["R", "A", "N", "A", "Z", "T", "B", "C", "D", "E"],
      ["F", "G", "H", "I", "J", "O", "L", "M", "N", "O"],
      ["P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y"],
      ["Z", "A", "B", "C", "D", "E", "F", "G", "H", "I"],
    ],
  },
  // Exercise 2: Colors
  {
    id: "ws-2",
    type: "word-search",
    title: "SOPA DE LETRAS - COLORES",
    instructions: "ENCUENTRA LOS COLORES ESCONDIDOS",
    gridSize: 10,
    words: ["ROJO", "AZUL", "VERDE", "ROSA", "GRIS"],
    wordPositions: [
      { word: "ROJO", startRow: 0, startCol: 2, direction: "horizontal" },
      { word: "AZUL", startRow: 2, startCol: 0, direction: "vertical" },
      { word: "VERDE", startRow: 2, startCol: 5, direction: "horizontal" },
      { word: "ROSA", startRow: 5, startCol: 3, direction: "horizontal" },
      { word: "GRIS", startRow: 6, startCol: 6, direction: "vertical" },
    ],
    grid: [
      ["X", "Y", "R", "O", "J", "O", "K", "L", "M", "N"],
      ["O", "P", "Q", "R", "S", "T", "U", "V", "W", "X"],
      ["A", "B", "C", "D", "E", "V", "E", "R", "D", "E"],
      ["Z", "F", "G", "H", "I", "J", "K", "L", "M", "N"],
      ["U", "O", "P", "Q", "R", "S", "T", "U", "V", "W"],
      ["L", "X", "Y", "R", "O", "S", "A", "B", "C", "D"],
      ["E", "F", "G", "H", "I", "J", "G", "K", "L", "M"],
      ["N", "O", "P", "Q", "R", "S", "R", "T", "U", "V"],
      ["W", "X", "Y", "Z", "A", "B", "I", "C", "D", "E"],
      ["F", "G", "H", "I", "J", "K", "S", "L", "M", "N"],
    ],
  },
  // Exercise 3: Food
  {
    id: "ws-3",
    type: "word-search",
    title: "SOPA DE LETRAS - COMIDA",
    instructions: "ENCUENTRA LAS PALABRAS DE COMIDA ESCONDIDAS",
    gridSize: 10,
    words: ["PAN", "LECHE", "AGUA", "MIEL", "SOPA"],
    wordPositions: [
      { word: "PAN", startRow: 1, startCol: 0, direction: "horizontal" },
      { word: "LECHE", startRow: 1, startCol: 9, direction: "vertical" },
      { word: "AGUA", startRow: 3, startCol: 2, direction: "horizontal" },
      { word: "MIEL", startRow: 6, startCol: 0, direction: "horizontal" },
      { word: "SOPA", startRow: 5, startCol: 7, direction: "vertical" },
    ],
    grid: [
      ["X", "Y", "Z", "A", "B", "L", "C", "D", "E", "F"],
      ["P", "A", "N", "G", "H", "E", "I", "J", "K", "L"],
      ["M", "N", "O", "P", "Q", "C", "R", "S", "T", "E"],
      ["V", "W", "A", "G", "U", "A", "X", "Y", "Z", "C"],
      ["B", "C", "D", "E", "F", "E", "G", "H", "I", "H"],
      ["K", "L", "M", "N", "O", "P", "Q", "S", "R", "E"],
      ["M", "I", "E", "L", "T", "U", "V", "O", "W", "X"],
      ["Y", "Z", "A", "B", "C", "D", "E", "P", "F", "G"],
      ["H", "I", "J", "K", "L", "M", "N", "A", "O", "P"],
      ["Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
    ],
  },
  // Exercise 4: Body parts
  {
    id: "ws-4",
    type: "word-search",
    title: "SOPA DE LETRAS - CUERPO",
    instructions: "ENCUENTRA LAS PARTES DEL CUERPO ESCONDIDAS",
    gridSize: 10,
    words: ["MANO", "PIE", "OJO", "BOCA", "DEDO"],
    wordPositions: [
      { word: "MANO", startRow: 0, startCol: 0, direction: "horizontal" },
      { word: "PIE", startRow: 2, startCol: 7, direction: "horizontal" },
      { word: "OJO", startRow: 4, startCol: 2, direction: "horizontal" },
      { word: "BOCA", startRow: 3, startCol: 0, direction: "vertical" },
      { word: "DEDO", startRow: 7, startCol: 3, direction: "horizontal" },
    ],
    grid: [
      ["M", "A", "N", "O", "X", "Y", "Z", "A", "B", "C"],
      ["D", "E", "F", "G", "H", "I", "J", "K", "L", "M"],
      ["N", "O", "P", "Q", "R", "S", "T", "P", "I", "E"],
      ["B", "U", "V", "W", "X", "Y", "Z", "A", "B", "C"],
      ["O", "D", "O", "J", "O", "E", "F", "G", "H", "I"],
      ["C", "J", "K", "L", "M", "N", "O", "P", "Q", "R"],
      ["A", "S", "T", "U", "V", "W", "X", "Y", "Z", "A"],
      ["B", "C", "D", "D", "E", "D", "O", "E", "F", "G"],
      ["H", "I", "J", "K", "L", "M", "N", "O", "P", "Q"],
      ["R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A"],
    ],
  },
  // Exercise 5: Nature
  {
    id: "ws-5",
    type: "word-search",
    title: "SOPA DE LETRAS - NATURALEZA",
    instructions: "ENCUENTRA LAS PALABRAS DE NATURALEZA",
    gridSize: 10,
    words: ["SOL", "LUNA", "FLOR", "ARBOL", "MAR"],
    wordPositions: [
      { word: "SOL", startRow: 0, startCol: 0, direction: "horizontal" },
      { word: "LUNA", startRow: 1, startCol: 5, direction: "horizontal" },
      { word: "FLOR", startRow: 3, startCol: 2, direction: "vertical" },
      { word: "ARBOL", startRow: 4, startCol: 5, direction: "horizontal" },
      { word: "MAR", startRow: 8, startCol: 1, direction: "horizontal" },
    ],
    grid: [
      ["S", "O", "L", "X", "Y", "Z", "A", "B", "C", "D"],
      ["E", "F", "G", "H", "I", "L", "U", "N", "A", "J"],
      ["K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"],
      ["U", "V", "F", "W", "X", "Y", "Z", "A", "B", "C"],
      ["D", "E", "L", "F", "G", "A", "R", "B", "O", "L"],
      ["H", "I", "O", "J", "K", "L", "M", "N", "O", "P"],
      ["Q", "R", "R", "S", "T", "U", "V", "W", "X", "Y"],
      ["Z", "A", "B", "C", "D", "E", "F", "G", "H", "I"],
      ["J", "M", "A", "R", "K", "L", "M", "N", "O", "P"],
      ["Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
    ],
  },
  // Exercise 6: Family
  {
    id: "ws-6",
    type: "word-search",
    title: "SOPA DE LETRAS - FAMILIA",
    instructions: "ENCUENTRA LAS PALABRAS DE FAMILIA",
    gridSize: 10,
    words: ["MAMA", "PAPA", "HIJO", "TIA", "BEBE"],
    wordPositions: [
      { word: "MAMA", startRow: 0, startCol: 3, direction: "horizontal" },
      { word: "PAPA", startRow: 2, startCol: 0, direction: "horizontal" },
      { word: "HIJO", startRow: 1, startCol: 6, direction: "vertical" },
      { word: "TIA", startRow: 5, startCol: 2, direction: "horizontal" },
      { word: "BEBE", startRow: 7, startCol: 5, direction: "horizontal" },
    ],
    grid: [
      ["X", "Y", "Z", "M", "A", "M", "A", "B", "C", "D"],
      ["E", "F", "G", "I", "J", "K", "H", "L", "M", "N"],
      ["P", "A", "P", "A", "O", "P", "I", "Q", "R", "S"],
      ["T", "U", "V", "W", "X", "Y", "J", "Z", "A", "B"],
      ["C", "D", "E", "F", "G", "H", "O", "I", "J", "K"],
      ["L", "M", "T", "I", "A", "N", "O", "P", "Q", "R"],
      ["S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B"],
      ["C", "D", "E", "F", "G", "B", "E", "B", "E", "H"],
      ["I", "J", "K", "L", "M", "N", "O", "P", "Q", "R"],
      ["S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B"],
    ],
  },
  // Exercise 7: School
  {
    id: "ws-7",
    type: "word-search",
    title: "SOPA DE LETRAS - ESCUELA",
    instructions: "ENCUENTRA LAS PALABRAS DE LA ESCUELA",
    gridSize: 10,
    words: ["LIBRO", "MESA", "LAPIZ", "GOMA", "TIZA"],
    wordPositions: [
      { word: "LIBRO", startRow: 0, startCol: 0, direction: "horizontal" },
      { word: "MESA", startRow: 2, startCol: 4, direction: "horizontal" },
      { word: "LAPIZ", startRow: 1, startCol: 0, direction: "vertical" },
      { word: "GOMA", startRow: 6, startCol: 2, direction: "horizontal" },
      { word: "TIZA", startRow: 4, startCol: 6, direction: "vertical" },
    ],
    grid: [
      ["L", "I", "B", "R", "O", "X", "Y", "Z", "A", "B"],
      ["L", "C", "D", "E", "F", "G", "H", "I", "J", "K"],
      ["A", "M", "N", "O", "M", "E", "S", "A", "P", "Q"],
      ["P", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
      ["I", "A", "B", "C", "D", "E", "T", "F", "G", "H"],
      ["Z", "I", "J", "K", "L", "M", "I", "N", "O", "P"],
      ["Q", "R", "G", "O", "M", "A", "Z", "S", "T", "U"],
      ["V", "W", "X", "Y", "Z", "A", "A", "B", "C", "D"],
      ["E", "F", "G", "H", "I", "J", "K", "L", "M", "N"],
      ["O", "P", "Q", "R", "S", "T", "U", "V", "W", "X"],
    ],
  },
  // Exercise 8: House
  {
    id: "ws-8",
    type: "word-search",
    title: "SOPA DE LETRAS - CASA",
    instructions: "ENCUENTRA LAS PARTES DE LA CASA",
    gridSize: 10,
    words: ["CAMA", "SALA", "TECHO", "PISO", "MESA"],
    wordPositions: [
      { word: "CAMA", startRow: 0, startCol: 2, direction: "horizontal" },
      { word: "SALA", startRow: 2, startCol: 0, direction: "horizontal" },
      { word: "TECHO", startRow: 1, startCol: 4, direction: "vertical" },
      { word: "PISO", startRow: 5, startCol: 0, direction: "horizontal" },
      { word: "MESA", startRow: 7, startCol: 5, direction: "horizontal" },
    ],
    grid: [
      ["X", "Y", "C", "A", "M", "A", "Z", "A", "B", "C"],
      ["D", "E", "F", "G", "T", "H", "I", "J", "K", "L"],
      ["S", "A", "L", "A", "E", "M", "N", "O", "P", "Q"],
      ["R", "S", "T", "U", "C", "V", "W", "X", "Y", "Z"],
      ["A", "B", "C", "D", "H", "E", "F", "G", "H", "I"],
      ["P", "I", "S", "O", "O", "J", "K", "L", "M", "N"],
      ["O", "P", "Q", "R", "S", "T", "U", "V", "W", "X"],
      ["Y", "Z", "A", "B", "C", "M", "E", "S", "A", "D"],
      ["E", "F", "G", "H", "I", "J", "K", "L", "M", "N"],
      ["O", "P", "Q", "R", "S", "T", "U", "V", "W", "X"],
    ],
  },
  // Exercise 9: Toys
  {
    id: "ws-9",
    type: "word-search",
    title: "SOPA DE LETRAS - JUGUETES",
    instructions: "ENCUENTRA LOS JUGUETES ESCONDIDOS",
    gridSize: 10,
    words: ["PELOTA", "CARRO", "DADO", "OSO", "TREN"],
    wordPositions: [
      { word: "PELOTA", startRow: 0, startCol: 1, direction: "horizontal" },
      { word: "CARRO", startRow: 2, startCol: 0, direction: "horizontal" },
      { word: "DADO", startRow: 4, startCol: 3, direction: "horizontal" },
      { word: "OSO", startRow: 5, startCol: 0, direction: "vertical" },
      { word: "TREN", startRow: 8, startCol: 5, direction: "horizontal" },
    ],
    grid: [
      ["X", "P", "E", "L", "O", "T", "A", "Y", "Z", "A"],
      ["B", "C", "D", "E", "F", "G", "H", "I", "J", "K"],
      ["C", "A", "R", "R", "O", "L", "M", "N", "O", "P"],
      ["Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
      ["A", "B", "C", "D", "A", "D", "O", "D", "E", "F"],
      ["O", "G", "H", "I", "J", "K", "L", "M", "N", "O"],
      ["S", "P", "Q", "R", "S", "T", "U", "V", "W", "X"],
      ["O", "Y", "Z", "A", "B", "C", "D", "E", "F", "G"],
      ["H", "I", "J", "K", "L", "T", "R", "E", "N", "M"],
      ["N", "O", "P", "Q", "R", "S", "T", "U", "V", "W"],
    ],
  },
  // Exercise 10: Weather
  {
    id: "ws-10",
    type: "word-search",
    title: "SOPA DE LETRAS - CLIMA",
    instructions: "ENCUENTRA LAS PALABRAS DEL CLIMA",
    gridSize: 10,
    words: ["LLUVIA", "NIEVE", "NUBE", "FRIO", "SOL"],
    wordPositions: [
      { word: "LLUVIA", startRow: 0, startCol: 0, direction: "horizontal" },
      { word: "NIEVE", startRow: 2, startCol: 4, direction: "horizontal" },
      { word: "NUBE", startRow: 4, startCol: 5, direction: "horizontal" },
      { word: "FRIO", startRow: 6, startCol: 2, direction: "horizontal" },
      { word: "SOL", startRow: 8, startCol: 0, direction: "horizontal" },
    ],
    grid: [
      ["L", "L", "U", "V", "I", "A", "X", "Y", "Z", "A"],
      ["B", "C", "D", "E", "F", "G", "H", "I", "J", "K"],
      ["L", "M", "N", "O", "N", "I", "E", "V", "E", "P"],
      ["Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
      ["A", "B", "C", "D", "E", "N", "U", "B", "E", "F"],
      ["G", "H", "I", "J", "K", "L", "M", "N", "O", "P"],
      ["Q", "R", "F", "R", "I", "O", "S", "T", "U", "V"],
      ["W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F"],
      ["S", "O", "L", "G", "H", "I", "J", "K", "L", "M"],
      ["N", "O", "P", "Q", "R", "S", "T", "U", "V", "W"],
    ],
  },
];

// Pictogram Crossword Exercises (Crucigramas con pictogramas)
// Copied exactly from edufichas.com PDF
// Grid legend: "" = fillable cell, null = blocked cell, "X" = pre-filled letter

const pictogramCrosswordExercises: PictogramCrosswordExercise[] = [
  {
    "id": "pc-1",
    "type": "pictogram-crossword",
    "title": "CRUCIGRAMA 1",
    "instructions": "ESCRIBE EL NOMBRE DE CADA IMAGEN",
    "gridSize": {
      "rows": 11,
      "cols": 9
    },
    "words": [
      {
        "word": "DIAMANTE",
        "emoji": "💎",
        "startRow": 3,
        "startCol": 1,
        "direction": "horizontal",
        "clueNumber": 1
      },
      {
        "word": "CORAZON",
        "emoji": "❤️",
        "startRow": 0,
        "startCol": 3,
        "direction": "vertical",
        "clueNumber": 2
      },
      {
        "word": "CACTUS",
        "emoji": "🌵",
        "startRow": 0,
        "startCol": 3,
        "direction": "horizontal",
        "clueNumber": 3
      },
      {
        "word": "PASTEL",
        "emoji": "🍰",
        "startRow": 2,
        "startCol": 5,
        "direction": "vertical",
        "clueNumber": 4
      },
      {
        "word": "GLOBO",
        "emoji": "🎈",
        "startRow": 7,
        "startCol": 4,
        "direction": "horizontal",
        "clueNumber": 5
      },
      {
        "word": "GATO",
        "emoji": "🐱",
        "startRow": 7,
        "startCol": 4,
        "direction": "vertical",
        "clueNumber": 6
      },
      {
        "word": "PIÑA",
        "emoji": "🍍",
        "startRow": 8,
        "startCol": 1,
        "direction": "horizontal",
        "clueNumber": 7
      },
      {
        "word": "RAYO",
        "emoji": "⚡",
        "startRow": 1,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 8
      }
    ],
    "grid": [
      [
        null,
        null,
        null,
        "",
        "",
        "C",
        "",
        "U",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null
      ],
      [
        null,
        "",
        "I",
        "",
        "",
        "",
        "",
        "",
        "E"
      ],
      [
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        "",
        "",
        "",
        ""
      ],
      [
        null,
        "",
        "",
        "",
        "",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null
      ]
    ]
  },
  {
    "id": "pc-2",
    "type": "pictogram-crossword",
    "title": "CRUCIGRAMA 2",
    "instructions": "ESCRIBE EL NOMBRE DE CADA IMAGEN",
    "gridSize": {
      "rows": 10,
      "cols": 15
    },
    "words": [
      {
        "word": "UNICORNIO",
        "emoji": "🦄",
        "startRow": 4,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 1
      },
      {
        "word": "ESTRELLAS",
        "emoji": "⭐⭐",
        "startRow": 1,
        "startCol": 5,
        "direction": "vertical",
        "clueNumber": 2
      },
      {
        "word": "ELEFANTE",
        "emoji": "🐘",
        "startRow": 1,
        "startCol": 5,
        "direction": "horizontal",
        "clueNumber": 3
      },
      {
        "word": "HELADO",
        "emoji": "🍦",
        "startRow": 0,
        "startCol": 12,
        "direction": "vertical",
        "clueNumber": 4
      },
      {
        "word": "FOCA",
        "emoji": "🦭",
        "startRow": 3,
        "startCol": 8,
        "direction": "vertical",
        "clueNumber": 5
      },
      {
        "word": "GATO",
        "emoji": "🐱",
        "startRow": 8,
        "startCol": 4,
        "direction": "horizontal",
        "clueNumber": 6
      },
      {
        "word": "NUBE",
        "emoji": "☁️",
        "startRow": 4,
        "startCol": 1,
        "direction": "vertical",
        "clueNumber": 7
      },
      {
        "word": "OSO",
        "emoji": "🐻",
        "startRow": 5,
        "startCol": 12,
        "direction": "horizontal",
        "clueNumber": 8
      }
    ],
    "grid": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        "",
        null,
        null
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "N",
        "",
        "O",
        null,
        null,
        null,
        "",
        null,
        null
      ],
      [
        null,
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        "",
        "",
        ""
      ],
      [
        null,
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "",
        null,
        null,
        null,
        "L",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        "",
        "",
        "O",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ]
  },
  {
    "id": "pc-3",
    "type": "pictogram-crossword",
    "title": "CRUCIGRAMA 3",
    "instructions": "ESCRIBE EL NOMBRE DE CADA IMAGEN",
    "gridSize": {
      "rows": 10,
      "cols": 13
    },
    "words": [
      {
        "word": "MENSAJE",
        "emoji": "💬",
        "startRow": 1,
        "startCol": 4,
        "direction": "horizontal",
        "clueNumber": 1
      },
      {
        "word": "LABIOS",
        "emoji": "👄",
        "startRow": 0,
        "startCol": 8,
        "direction": "vertical",
        "clueNumber": 2
      },
      {
        "word": "HELADO",
        "emoji": "🍦",
        "startRow": 0,
        "startCol": 5,
        "direction": "vertical",
        "clueNumber": 3
      },
      {
        "word": "ZAPATO",
        "emoji": "👟",
        "startRow": 5,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 4
      },
      {
        "word": "CORONA",
        "emoji": "👑",
        "startRow": 4,
        "startCol": 7,
        "direction": "horizontal",
        "clueNumber": 5
      },
      {
        "word": "FRESA",
        "emoji": "🍓",
        "startRow": 3,
        "startCol": 1,
        "direction": "horizontal",
        "clueNumber": 6
      },
      {
        "word": "LLAVE",
        "emoji": "🔑",
        "startRow": 2,
        "startCol": 12,
        "direction": "vertical",
        "clueNumber": 7
      },
      {
        "word": "PIZZA",
        "emoji": "🍕",
        "startRow": 5,
        "startCol": 2,
        "direction": "vertical",
        "clueNumber": 8
      }
    ],
    "grid": [
      [
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        "",
        "N",
        "",
        "",
        "J",
        "",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        ""
      ],
      [
        null,
        "F",
        "",
        "",
        "",
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        ""
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        ""
      ],
      [
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        ""
      ],
      [
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "Z",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ]
  },
  {
    "id": "pc-4",
    "type": "pictogram-crossword",
    "title": "CRUCIGRAMA 4",
    "instructions": "ESCRIBE EL NOMBRE DE CADA IMAGEN",
    "gridSize": {
      "rows": 11,
      "cols": 17
    },
    "words": [
      {
        "word": "ZANAHORIA",
        "emoji": "🥕",
        "startRow": 1,
        "startCol": 3,
        "direction": "horizontal",
        "clueNumber": 1
      },
      {
        "word": "SALCHICHA",
        "emoji": "🌭",
        "startRow": 0,
        "startCol": 4,
        "direction": "vertical",
        "clueNumber": 2
      },
      {
        "word": "MAGDALENA",
        "emoji": "🧁",
        "startRow": 0,
        "startCol": 6,
        "direction": "vertical",
        "clueNumber": 3
      },
      {
        "word": "GALLETA",
        "emoji": "🍪",
        "startRow": 0,
        "startCol": 11,
        "direction": "vertical",
        "clueNumber": 4
      },
      {
        "word": "MANZANA",
        "emoji": "🍎",
        "startRow": 6,
        "startCol": 10,
        "direction": "horizontal",
        "clueNumber": 5
      },
      {
        "word": "PASTEL",
        "emoji": "🍰",
        "startRow": 5,
        "startCol": 14,
        "direction": "vertical",
        "clueNumber": 6
      },
      {
        "word": "LECHE",
        "emoji": "🥛",
        "startRow": 2,
        "startCol": 11,
        "direction": "horizontal",
        "clueNumber": 7
      },
      {
        "word": "PIZZA",
        "emoji": "🍕",
        "startRow": 8,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 8
      }
    ],
    "grid": [
      [
        null,
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "",
        "A",
        "",
        "",
        "",
        "O",
        "",
        "",
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null,
        null,
        "",
        "",
        "",
        "",
        "",
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "I",
        null,
        "",
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "C",
        null,
        "",
        null,
        null,
        null,
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        null,
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null
      ],
      [
        "",
        "",
        "",
        "",
        "",
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null
      ]
    ]
  },
  {
    "id": "pc-5",
    "type": "pictogram-crossword",
    "title": "CRUCIGRAMA 5",
    "instructions": "ESCRIBE EL NOMBRE DE CADA IMAGEN",
    "gridSize": {
      "rows": 9,
      "cols": 13
    },
    "words": [
      {
        "word": "CANGREJO",
        "emoji": "🦀",
        "startRow": 3,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 1
      },
      {
        "word": "BOTELLA",
        "emoji": "🍾",
        "startRow": 2,
        "startCol": 7,
        "direction": "vertical",
        "clueNumber": 2
      },
      {
        "word": "PIRATA",
        "emoji": "🏴‍☠️",
        "startRow": 1,
        "startCol": 4,
        "direction": "vertical",
        "clueNumber": 3
      },
      {
        "word": "TESORO",
        "emoji": "💰🏴‍☠️",
        "startRow": 4,
        "startCol": 7,
        "direction": "horizontal",
        "clueNumber": 4
      },
      {
        "word": "MEDUSA",
        "emoji": "🪼",
        "startRow": 0,
        "startCol": 9,
        "direction": "vertical",
        "clueNumber": 5
      },
      {
        "word": "SIRENA",
        "emoji": "🧜‍♀️",
        "startRow": 2,
        "startCol": 11,
        "direction": "vertical",
        "clueNumber": 6
      },
      {
        "word": "PECES",
        "emoji": "🐟🐟",
        "startRow": 1,
        "startCol": 0,
        "direction": "vertical",
        "clueNumber": 7
      },
      {
        "word": "MAPA",
        "emoji": "🗺️",
        "startRow": 0,
        "startCol": 9,
        "direction": "horizontal",
        "clueNumber": 8
      }
    ],
    "grid": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        "A",
        "",
        ""
      ],
      [
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null
      ],
      [
        "E",
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        "",
        null,
        "",
        null
      ],
      [
        "",
        "A",
        "",
        "",
        "",
        "",
        "",
        "",
        null,
        "",
        null,
        "",
        null
      ],
      [
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        "",
        null,
        "",
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        "N",
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        "",
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ]
    ]
  },
  {
    "id": "pc-6",
    "type": "pictogram-crossword",
    "title": "CRUCIGRAMA 6",
    "instructions": "ESCRIBE EL NOMBRE DE CADA IMAGEN",
    "gridSize": {
      "rows": 15,
      "cols": 9
    },
    "words": [
      {
        "word": "PRINCESA",
        "emoji": "👸",
        "startRow": 7,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 1
      },
      {
        "word": "CASTILLO",
        "emoji": "🏰",
        "startRow": 7,
        "startCol": 4,
        "direction": "vertical",
        "clueNumber": 2
      },
      {
        "word": "PRINCIPE",
        "emoji": "🤴",
        "startRow": 7,
        "startCol": 0,
        "direction": "vertical",
        "clueNumber": 3
      },
      {
        "word": "MANZANA",
        "emoji": "🍎",
        "startRow": 6,
        "startCol": 7,
        "direction": "vertical",
        "clueNumber": 4
      },
      {
        "word": "DRAGON",
        "emoji": "🐉",
        "startRow": 2,
        "startCol": 3,
        "direction": "vertical",
        "clueNumber": 5
      },
      {
        "word": "ESPADA",
        "emoji": "🗡️",
        "startRow": 4,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 6
      },
      {
        "word": "BRUJA",
        "emoji": "🧙‍♀️",
        "startRow": 0,
        "startCol": 5,
        "direction": "vertical",
        "clueNumber": 7
      },
      {
        "word": "RANA",
        "emoji": "🐸",
        "startRow": 1,
        "startCol": 5,
        "direction": "horizontal",
        "clueNumber": 8
      }
    ],
    "grid": [
      [
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "",
        "",
        "",
        "A"
      ],
      [
        null,
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "",
        null,
        "J",
        null,
        null,
        null
      ],
      [
        "",
        "S",
        "",
        "",
        "",
        "",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        "",
        null
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        null
      ],
      [
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null
      ],
      [
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null
      ],
      [
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null
      ],
      [
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null
      ],
      [
        "",
        null,
        null,
        null,
        "L",
        null,
        null,
        "",
        null
      ],
      [
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null
      ],
      [
        "",
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null
      ]
    ]
  },
  {
    "id": "pc-7",
    "type": "pictogram-crossword",
    "title": "CRUCIGRAMA 7",
    "instructions": "ESCRIBE EL NOMBRE DE CADA IMAGEN",
    "gridSize": {
      "rows": 13,
      "cols": 11
    },
    "words": [
      {
        "word": "ELEFANTE",
        "emoji": "🐘",
        "startRow": 3,
        "startCol": 3,
        "direction": "horizontal",
        "clueNumber": 1
      },
      {
        "word": "DOMADOR",
        "emoji": "🎩⭕️🦁",
        "startRow": 0,
        "startCol": 7,
        "direction": "vertical",
        "clueNumber": 2
      },
      {
        "word": "GLOBOS",
        "emoji": "🎈🎈",
        "startRow": 2,
        "startCol": 4,
        "direction": "vertical",
        "clueNumber": 3
      },
      {
        "word": "PAYASO",
        "emoji": "🤡",
        "startRow": 7,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 4
      },
      {
        "word": "CAÑON",
        "emoji": "🎉💥🪖",
        "startRow": 6,
        "startCol": 1,
        "direction": "vertical",
        "clueNumber": 5
      },
      {
        "word": "CARPA",
        "emoji": "🎪",
        "startRow": 12,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 6
      },
      {
        "word": "FOCA",
        "emoji": "🦭",
        "startRow": 1,
        "startCol": 6,
        "direction": "horizontal",
        "clueNumber": 7
      },
      {
        "word": "MONO",
        "emoji": "🐵",
        "startRow": 5,
        "startCol": 6,
        "direction": "horizontal",
        "clueNumber": 8
      }
    ],
    "grid": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        "",
        "",
        "",
        null
      ],
      [
        null,
        null,
        null,
        null,
        "G",
        null,
        null,
        "",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "",
        null,
        "",
        "",
        "N",
        "",
        null
      ],
      [
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "O",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "C",
        "",
        "",
        "",
        "",
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ]
  },
  {
    "id": "pc-8",
    "type": "pictogram-crossword",
    "title": "CRUCIGRAMA 8",
    "instructions": "ESCRIBE EL NOMBRE DE CADA IMAGEN",
    "gridSize": {
      "rows": 13,
      "cols": 14
    },
    "words": [
      {
        "word": "CALCULADORA",
        "emoji": "🔢🧮",
        "startRow": 1,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 1
      },
      {
        "word": "CALENDARIO",
        "emoji": "📆",
        "startRow": 1,
        "startCol": 0,
        "direction": "vertical",
        "clueNumber": 2
      },
      {
        "word": "CUADERNOS",
        "emoji": "📒📒",
        "startRow": 1,
        "startCol": 3,
        "direction": "vertical",
        "clueNumber": 3
      },
      {
        "word": "MOCHILA",
        "emoji": "🎒",
        "startRow": 0,
        "startCol": 8,
        "direction": "vertical",
        "clueNumber": 4
      },
      {
        "word": "PIZARRA",
        "emoji": "👩‍🏫✍️",
        "startRow": 4,
        "startCol": 7,
        "direction": "horizontal",
        "clueNumber": 5
      },
      {
        "word": "ESTUCHE",
        "emoji": "🧰✏️",
        "startRow": 9,
        "startCol": 2,
        "direction": "horizontal",
        "clueNumber": 6
      },
      {
        "word": "LIBROS",
        "emoji": "📚",
        "startRow": 1,
        "startCol": 5,
        "direction": "vertical",
        "clueNumber": 7
      },
      {
        "word": "LAPIZ",
        "emoji": "✏️",
        "startRow": 12,
        "startCol": 0,
        "direction": "horizontal",
        "clueNumber": 8
      }
    ],
    "grid": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        "C",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        null,
        null,
        null
      ],
      [
        "",
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        "",
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        "",
        null,
        null,
        "",
        null,
        "",
        null,
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        "",
        null,
        null,
        "",
        null,
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        "",
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "R",
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "",
        null,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        null,
        null,
        null,
        null,
        null
      ],
      [
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "L",
        "",
        "",
        "",
        "Z",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ]
  }
]
;

// Export exercise sets for Spanish
export const castellanoExerciseSets: ExerciseSet[] = [
  {
    id: "sopa-letras-1",
    title: "SOPA DE LETRAS - NIVEL 1",
    icon: "🔤",
    exercises: wordSearchExercises.slice(0, 5),
  },
  {
    id: "sopa-letras-2",
    title: "SOPA DE LETRAS - NIVEL 2",
    icon: "🔡",
    exercises: wordSearchExercises.slice(5, 10),
  },
  {
    id: "crucigrama-1",
    title: "CRUCIGRAMA - NIVEL 1",
    icon: "📝",
    exercises: pictogramCrosswordExercises.slice(0, 5),
  },
  {
    id: "crucigrama-2",
    title: "CRUCIGRAMA - NIVEL 2",
    icon: "✏️",
    exercises: pictogramCrosswordExercises.slice(5, 10),
  },
];
