import { ExerciseSet } from "./types";

export const matematiquesExerciseSets: ExerciseSet[] = [
  {
    id: "set-21",
    title: "COMPTEM",
    icon: "🔢",
    exercises: [
      {
        id: "21-1",
        type: "number-sequence",
        title: "COMPTEM ENDAVANT",
        instructions: "ESCRIU EL NOMBRE QUE VA AL FINAL DE LA SÈRIE",
        start: 5,
        direction: "forward",
        step: 1,
        length: 5,
        missingIndices: [4],
      },
      {
        id: "21-2",
        type: "number-sequence",
        title: "COMPTEM ENRERE",
        instructions: "ESCRIU EL NOMBRE QUE VA AL PRINCIPI DE LA SÈRIE",
        start: 12,
        direction: "backward",
        step: 1,
        length: 5,
        missingIndices: [0],
      },
      {
        id: "21-3",
        type: "number-sequence",
        title: "COMPTEM DE 10 EN 10",
        instructions: "COMPLETA LES SÈRIES COMPTANT DE 2 EN 2",
        start: 2,
        direction: "forward",
        step: 2,
        length: 6,
        missingIndices: [2, 4, 5],
      },
      {
        id: "21-4",
        type: "number-sequence",
        title: "COMPTEM ENDAVANT",
        instructions: "COMPLETA LA SÈRIE",
        start: 7,
        direction: "forward",
        step: 1,
        length: 6,
        missingIndices: [2, 4],
      },
      {
        id: "21-5",
        type: "number-sequence",
        title: "COMPTEM ENRERE",
        instructions: "COMPLETA LA SÈRIE",
        start: 15,
        direction: "backward",
        step: 1,
        length: 6,
        missingIndices: [1, 3, 5],
      },
      {
        id: "21-6",
        type: "number-sequence",
        title: "COMPTEM DE 10 EN 10",
        instructions: "COMPLETA LES SÈRIES COMPTANT DE 3 EN 3",
        start: 3,
        direction: "forward",
        step: 3,
        length: 6,
        missingIndices: [1, 3, 5],
      },
      {
        id: "21-7",
        type: "number-sequence",
        title: "COMPTEM ENDAVANT",
        instructions: "COMPLETA LA SÈRIE",
        start: 4,
        direction: "forward",
        step: 1,
        length: 7,
        missingIndices: [2, 4, 6],
      },
      {
        id: "21-8",
        type: "number-sequence",
        title: "COMPTEM ENRERE",
        instructions: "COMPLETA LA SÈRIE",
        start: 19,
        direction: "backward",
        step: 1,
        length: 7,
        missingIndices: [1, 3, 5],
      },
      {
        id: "21-9",
        type: "number-sequence",
        title: "COMPTEM DE 10 EN 10",
        instructions: "COMPLETA LES SÈRIES COMPTANT DE 4 EN 4",
        start: 4,
        direction: "forward",
        step: 4,
        length: 5,
        missingIndices: [1, 3],
      },
      {
        id: "21-10",
        type: "number-sequence",
        title: "COMPTEM DE 5 EN 5",
        instructions: "COMPLETA LA SÈRIE",
        start: 5,
        direction: "forward",
        step: 5,
        length: 4,
        missingIndices: [1, 3],
      },
    ],
  },
  {
    id: "set-22",
    title: "COMPTEM",
    icon: "🏢",
    exercises: [
      {
        id: "22-1",
        type: "counting",
        title: "PINTA FINESTRES",
        instructions: "COMPTA LES FINESTRES",
        items: "🪟",
        count: 12,
        imageType: "grid",
      },
      {
        id: "22-2",
        type: "counting",
        title: "PINTA FINESTRES",
        instructions: "COMPTA LES FINESTRES",
        items: "🪟",
        count: 15,
        imageType: "grid",
      },
      {
        id: "22-3",
        type: "counting",
        title: "COMPTA EUROS",
        instructions: "COMPTA I ESCRIU QUANTS EUROS HI HA",
        items: "💶",
        count: 18,
        imageType: "groups",
      },
      {
        id: "22-4",
        type: "counting",
        title: "COMPTA OUS",
        instructions: "COMPTA QUANTS OUS HI HA",
        items: "🥚",
        count: 10,
        imageType: "grid",
      },
      {
        id: "22-5",
        type: "counting",
        title: "COMPTA QUADRADETS",
        instructions: "COMPTA QUANTS QUADRADETS PINTATS HI HA",
        items: "🟨",
        count: 14,
        imageType: "grid",
      },
      {
        id: "22-6",
        type: "counting",
        title: "COMPTA DAUS",
        instructions: "COMPTA ELS PUNTS DELS DAUS",
        items: "🎲",
        count: 19,
        imageType: "groups",
      },
      {
        id: "22-7",
        type: "counting",
        title: "COMPTA POMES",
        instructions: "COMPTA LES POMES",
        items: "🍎",
        count: 13,
        imageType: "scattered",
      },
      {
        id: "22-8",
        type: "counting",
        title: "COMPTA ESTRELLES",
        instructions: "COMPTA LES ESTRELLES",
        items: "⭐",
        count: 16,
        imageType: "groups",
      },
      {
        id: "22-9",
        type: "counting",
        title: "COMPTA FLORS",
        instructions: "COMPTA LES FLORS",
        items: "🌸",
        count: 9,
        imageType: "grid",
      },
      {
        id: "22-10",
        type: "counting",
        title: "COMPTA PILOTES",
        instructions: "COMPTA LES PILOTES",
        items: "⚽",
        count: 8,
        imageType: "scattered",
      },
      {
        id: "22-11",
        type: "counting",
        title: "COMPTA CUBS",
        instructions: "COMPTA ELS CUBS",
        items: "🧊",
        count: 17,
        imageType: "grid",
      },
      {
        id: "22-12",
        type: "counting",
        title: "COMPTA MONEDES",
        instructions: "COMPTA LES MONEDES",
        items: "🪙",
        count: 20,
        imageType: "groups",
      },
    ],
  },
  {
    id: "set-23a",
    title: "ORDENA NOMBRES",
    icon: "📊",
    exercises: [
      {
        id: "23a-1",
        type: "number-order",
        title: "PINTA EL MÉS PETIT",
        instructions: "PINTA EL NOMBRE MÉS PETIT",
        numbers: [4, 9],
        question: "smallest",
      },
      {
        id: "23a-2",
        type: "number-order",
        title: "PINTA EL MÉS GRAN",
        instructions: "PINTA EL NOMBRE MÉS GRAN",
        numbers: [5, 12],
        question: "largest",
      },
      {
        id: "23a-3",
        type: "number-order",
        title: "PINTA EL MÉS PETIT",
        instructions: "PINTA EL NOMBRE MÉS PETIT",
        numbers: [6, 14, 11],
        question: "smallest",
      },
      {
        id: "23a-4",
        type: "number-order",
        title: "PINTA EL MÉS GRAN",
        instructions: "PINTA EL NOMBRE MÉS GRAN",
        numbers: [7, 10, 15],
        question: "largest",
      },
      {
        id: "23a-5",
        type: "number-order",
        title: "PINTA EL MÉS PETIT",
        instructions: "PINTA EL NOMBRE MÉS PETIT",
        numbers: [3, 16, 12, 9],
        question: "smallest",
      },
      {
        id: "23a-6",
        type: "number-order",
        title: "PINTA EL MÉS GRAN",
        instructions: "PINTA EL NOMBRE MÉS GRAN",
        numbers: [18, 5, 17, 8],
        question: "largest",
      },
      {
        id: "23a-7",
        type: "number-order",
        title: "ORDENA DE PETIT A GRAN",
        instructions: "ORDENA ELS NOMBRES DE PETIT A GRAN",
        numbers: [2, 5, 9, 12, 15, 19],
        question: "order-asc",
      },
      {
        id: "23a-8",
        type: "number-order",
        title: "ORDENA DE GRAN A PETIT",
        instructions: "ORDENA ELS NOMBRES DE GRAN A PETIT",
        numbers: [4, 11, 6, 13, 7, 19],
        question: "order-desc",
      },
      {
        id: "23a-9",
        type: "number-order",
        title: "ORDENA DE PETIT A GRAN",
        instructions: "ORDENA ELS NOMBRES DE PETIT A GRAN",
        numbers: [1, 8, 6, 14, 3, 10],
        question: "order-asc",
      },
      {
        id: "23a-10",
        type: "number-order",
        title: "ORDENA DE GRAN A PETIT",
        instructions: "ORDENA ELS NOMBRES DE GRAN A PETIT",
        numbers: [20, 17, 12, 9, 5, 15],
        question: "order-desc",
      },
      {
        id: "23a-11",
        type: "number-order",
        title: "ORDENA DE PETIT A GRAN",
        instructions: "ORDENA ELS NOMBRES DE PETIT A GRAN",
        numbers: [11, 2, 18, 5, 7],
        question: "order-asc",
      },
      {
        id: "23a-12",
        type: "number-order",
        title: "ORDENA DE GRAN A PETIT",
        instructions: "ORDENA ELS NOMBRES DE GRAN A PETIT",
        numbers: [16, 4, 19, 8, 14],
        question: "order-desc",
      },
    ],
  },
  {
    id: "set-23",
    title: "SUMEM 3 NOMBRES",
    icon: "➕",
    exercises: [
      {
        id: "23-1",
        type: "addition-three",
        title: "SUMA FORMIGUES",
        instructions: "SUMA I RESPON QUANTES FORMIGUES HI HA",
        numbers: [3, 4, 2],
        showVisual: true,
      },
      {
        id: "23-2",
        type: "addition-three",
        title: "OMPLE I SUMA",
        instructions: "OMPLE ELS BUITS I SUMA",
        numbers: [8, 2, 7],
      },
      {
        id: "23-3",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [9, 1, 6],
      },
      {
        id: "23-4",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [5, 6, 5],
      },
      {
        id: "23-5",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [3, 9, 4],
      },
      {
        id: "23-6",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [7, 5, 8],
      },
      {
        id: "23-7",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [6, 4, 9],
      },
      {
        id: "23-8",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [2, 8, 5],
      },
      {
        id: "23-9",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [4, 7, 6],
      },
      {
        id: "23-10",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [8, 3, 7],
      },
    ],
  },
  {
    id: "set-24",
    title: "RESTEM SALTANT",
    icon: "➖",
    exercises: [
      {
        id: "24-1",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 19,
        subtract: 4,
        steps: [19, 15],
      },
      {
        id: "24-2",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 17,
        subtract: 5,
        steps: [17, 12],
      },
      {
        id: "24-3",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 16,
        subtract: 3,
        steps: [16, 13],
      },
      {
        id: "24-4",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 18,
        subtract: 7,
        steps: [18, 11],
      },
      {
        id: "24-5",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 14,
        subtract: 6,
        steps: [14, 8],
      },
      {
        id: "24-6",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 13,
        subtract: 4,
        steps: [13, 9],
      },
      {
        id: "24-7",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 20,
        subtract: 8,
        steps: [20, 12],
      },
      {
        id: "24-8",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 15,
        subtract: 5,
        steps: [15, 10],
      },
      {
        id: "24-9",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 12,
        subtract: 3,
        steps: [12, 9],
      },
      {
        id: "24-10",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 11,
        subtract: 2,
        steps: [11, 9],
      },
    ],
  },
  {
    id: "set-25",
    title: "SUMEM SALTANT",
    icon: "🦘",
    exercises: [
      {
        id: "25-1",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 8,
        add: 7,
        steps: [8, 10, 15],
      },
      {
        id: "25-2",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 7,
        add: 6,
        steps: [7, 10, 13],
      },
      {
        id: "25-3",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 6,
        add: 8,
        steps: [6, 10, 14],
      },
      {
        id: "25-4",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 9,
        add: 5,
        steps: [9, 10, 14],
      },
      {
        id: "25-5",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 5,
        add: 9,
        steps: [5, 10, 14],
      },
      {
        id: "25-6",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 4,
        add: 8,
        steps: [4, 10, 12],
      },
      {
        id: "25-7",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 8,
        add: 9,
        steps: [8, 10, 17],
      },
      {
        id: "25-8",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 7,
        add: 8,
        steps: [7, 10, 15],
      },
      {
        id: "25-9",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 6,
        add: 7,
        steps: [6, 10, 13],
      },
      {
        id: "25-10",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 9,
        add: 6,
        steps: [9, 10, 15],
      },
    ],
  },
  {
    id: "set-26",
    title: "RESTEM SALTANT PEL 10",
    icon: "⬇️",
    exercises: [
      {
        id: "26-1",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 14,
        subtract: 6,
        steps: [14, 10, 8],
      },
      {
        id: "26-2",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 13,
        subtract: 7,
        steps: [13, 10, 6],
      },
      {
        id: "26-3",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 15,
        subtract: 8,
        steps: [15, 10, 7],
      },
      {
        id: "26-4",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 12,
        subtract: 5,
        steps: [12, 10, 7],
      },
      {
        id: "26-5",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 16,
        subtract: 9,
        steps: [16, 10, 7],
      },
      {
        id: "26-6",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 17,
        subtract: 8,
        steps: [17, 10, 9],
      },
      {
        id: "26-7",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 18,
        subtract: 9,
        steps: [18, 10, 9],
      },
      {
        id: "26-8",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 11,
        subtract: 4,
        steps: [11, 10, 7],
      },
      {
        id: "26-9",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 19,
        subtract: 7,
        steps: [19, 10, 12],
      },
      {
        id: "26-10",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 20,
        subtract: 8,
        steps: [20, 10, 12],
      },
    ],
  },
  {
    id: "set-27",
    title: "COMPTEM VAGONS",
    icon: "🚂",
    exercises: [
      {
        id: "27-1",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [8],
        missingPositions: [8],
        mode: "fill-signs",
      },
      {
        id: "27-2",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [7],
        missingPositions: [7],
        mode: "fill-signs",
      },
      {
        id: "27-3",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [6],
        missingPositions: [6],
        mode: "fill-signs",
      },
      {
        id: "27-4",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 12,
        signPositions: [12],
        missingPositions: [12],
        mode: "fill-signs",
      },
      {
        id: "27-5",
        type: "train-position",
        title: "POSA ELS CARTELLS",
        instructions: "POSA CADA CARTELL AL LLOC CORRECTE",
        trainLength: 10,
        signPositions: [1, 4, 7, 10],
        missingPositions: [1, 4, 7, 10],
        availableSigns: [1, 4, 7, 10],
        mode: "place-signs",
      },
      {
        id: "27-6",
        type: "train-position",
        title: "POSA ELS CARTELLS",
        instructions: "POSA CADA CARTELL AL LLOC CORRECTE",
        trainLength: 11,
        signPositions: [2, 5, 8, 11],
        missingPositions: [2, 5, 8, 11],
        availableSigns: [2, 5, 8, 11],
        mode: "place-signs",
      },
      {
        id: "27-7",
        type: "train-position",
        title: "POSA ELS CARTELLS",
        instructions: "POSA CADA CARTELL AL LLOC CORRECTE",
        trainLength: 10,
        signPositions: [3, 5, 7, 9],
        missingPositions: [3, 5, 7, 9],
        availableSigns: [3, 5, 7, 9],
        mode: "place-signs",
      },
      {
        id: "27-8",
        type: "train-position",
        title: "POSA ELS CARTELLS",
        instructions: "POSA CADA CARTELL AL LLOC CORRECTE",
        trainLength: 12,
        signPositions: [2, 4, 6, 8, 10],
        missingPositions: [2, 4, 6, 8, 10],
        availableSigns: [2, 4, 6, 8, 10],
        mode: "place-signs",
      },
      {
        id: "27-9",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "COMPLETA ELS CARTELLS FINS I TOT SOTA EL PONT",
        trainLength: 10,
        signPositions: [9],
        missingPositions: [9],
        tunnels: [
          {
            start: 2,
            length: 3,
            variant: "wood",
          },
        ],
        mode: "tunnel-fill",
      },
      {
        id: "27-10",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "COMPLETA ELS CARTELLS FINS I TOT SOTA EL PONT",
        trainLength: 11,
        signPositions: [10],
        missingPositions: [10],
        tunnels: [
          {
            start: 6,
            length: 3,
            variant: "stone",
          },
        ],
        mode: "tunnel-fill",
      },
      {
        id: "27-11",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "COMPLETA ELS CARTELLS FINS I TOT SOTA EL PONT",
        trainLength: 10,
        signPositions: [5],
        missingPositions: [5],
        tunnels: [
          {
            start: 2,
            length: 2,
            variant: "moss",
          },
        ],
        mode: "tunnel-fill",
      },
      {
        id: "27-12",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "COMPLETA ELS CARTELLS FINS I TOT SOTA EL PONT",
        trainLength: 12,
        signPositions: [7],
        missingPositions: [7],
        tunnels: [
          {
            start: 3,
            length: 4,
            variant: "stone",
          },
        ],
        mode: "tunnel-fill",
      },
    ],
  },
  {
    id: "set-31",
    title: "BUSQUEM NOMBRES",
    icon: "🔍",
    exercises: [
      {
        id: "31-1",
        type: "number-pattern",
        title: "ESCRIU ELS NOMBRES QUE FALTEN",
        instructions: "COMPLETA ELS ESPAIS BLANCS",
        patterns: [
          {
            layout: "line",
            given: [{ position: "0", value: 1 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 4 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 7 }],
            missing: ["0", "1"],
          },
        ],
      },
      {
        id: "31-2",
        type: "number-pattern",
        title: "OMPLE ELS ESPAIS BLANCS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "0", value: 6 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 9 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "0", value: 11 }],
            missing: ["1", "2"],
          },
        ],
      },
      {
        id: "31-3",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "2", value: 9 }],
            missing: ["0", "1"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 12 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "0", value: 14 }],
            missing: ["1", "2"],
          },
        ],
      },
      {
        id: "31-4",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "1", value: 5 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "0", value: 8 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 12 }],
            missing: ["0", "1"],
          },
        ],
      },
      {
        id: "31-5",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "0", value: 2 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 7 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 15 }],
            missing: ["0", "1"],
          },
        ],
      },
      {
        id: "31-6",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "0", value: 9 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 11 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 18 }],
            missing: ["0", "1"],
          },
        ],
      },
      {
        id: "31-7",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "1", value: 6 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 14 }],
            missing: ["0", "1"],
          },
          {
            layout: "line",
            given: [{ position: "0", value: 4 }],
            missing: ["1", "2"],
          },
        ],
      },
      {
        id: "31-8",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "1", value: 8 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "0", value: 13 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 17 }],
            missing: ["0", "1"],
          },
        ],
      },
      {
        id: "31-9",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "0", value: 3 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 10 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "0", value: 16 }],
            missing: ["1", "2"],
          },
        ],
      },
      {
        id: "31-10",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "1", value: 12 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 20 }],
            missing: ["0", "1"],
          },
          {
            layout: "line",
            given: [{ position: "0", value: 5 }],
            missing: ["1", "2"],
          },
        ],
      },
    ],
  },
  {
    id: "set-34",
    title: "QUADRATS MÀGICS",
    icon: "✨",
    exercises: [
      {
        id: "34-1",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 11,
        given: [
          { row: 0, col: 0, value: 5 },
          { row: 0, col: 2, value: 3 },
          { row: 1, col: 0, value: 4 },
          { row: 1, col: 2, value: 4 },
          { row: 2, col: 0, value: 2 },
          { row: 2, col: 1, value: 5 },
        ],
        validateRow: 0,
        validateColumn: 2,
      },
      {
        id: "34-2",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 12,
        given: [
          { row: 0, col: 0, value: 7 },
          { row: 0, col: 2, value: 5 },
          { row: 1, col: 0, value: 2 },
          { row: 1, col: 2, value: 6 },
          { row: 2, col: 0, value: 3 },
          { row: 2, col: 1, value: 8 },
        ],
        validateRow: 0,
        validateColumn: 2,
      },
      {
        id: "34-3",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 13,
        given: [
          { row: 0, col: 1, value: 4 },
          { row: 0, col: 2, value: 3 },
          { row: 1, col: 0, value: 2 },
          { row: 1, col: 2, value: 6 },
          { row: 2, col: 0, value: 5 },
          { row: 2, col: 1, value: 4 },
          { row: 2, col: 2, value: 4 },
        ],
        validateRow: 0,
        validateColumn: 2,
      },
      {
        id: "34-4",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 14,
        given: [
          { row: 0, col: 1, value: 5 },
          { row: 0, col: 2, value: 3 },
          { row: 1, col: 0, value: 4 },
          { row: 1, col: 1, value: 4 },
          { row: 1, col: 2, value: 6 },
          { row: 2, col: 0, value: 4 },
          { row: 2, col: 2, value: 5 },
        ],
        validateRow: 2,
        validateColumn: 0,
      },
      {
        id: "34-5",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 15,
        given: [
          { row: 0, col: 0, value: 8 },
          { row: 0, col: 2, value: 6 },
          { row: 1, col: 0, value: 3 },
          { row: 1, col: 2, value: 7 },
          { row: 2, col: 0, value: 4 },
          { row: 2, col: 1, value: 9 },
        ],
        validateRow: 0,
        validateColumn: 2,
      },
      {
        id: "34-6",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 16,
        given: [
          { row: 0, col: 0, value: 7 },
          { row: 0, col: 1, value: 5 },
          { row: 1, col: 0, value: 5 },
          { row: 1, col: 2, value: 5 },
          { row: 2, col: 0, value: 4 },
          { row: 2, col: 1, value: 5 },
        ],
        validateRow: 2,
        validateColumn: 2,
      },
      {
        id: "34-7",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 17,
        given: [
          { row: 0, col: 0, value: 8 },
          { row: 0, col: 1, value: 5 },
          { row: 1, col: 0, value: 6 },
          { row: 1, col: 2, value: 6 },
          { row: 2, col: 1, value: 7 },
          { row: 2, col: 2, value: 7 },
        ],
        validateRow: 0,
        validateColumn: 0,
      },
      {
        id: "34-8",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 18,
        given: [
          { row: 0, col: 0, value: 9 },
          { row: 0, col: 2, value: 7 },
          { row: 0, col: 1, value: 2 },
          { row: 1, col: 0, value: 4 },
          { row: 1, col: 2, value: 8 },
          { row: 2, col: 1, value: 10 },
        ],
        validateRow: 2,
        validateColumn: 0,
      },
      {
        id: "34-9",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 19,
        given: [
          { row: 0, col: 0, value: 9 },
          { row: 0, col: 2, value: 4 },
          { row: 1, col: 0, value: 7 },
          { row: 1, col: 2, value: 6 },
          { row: 2, col: 0, value: 3 },
          { row: 2, col: 1, value: 7 },
        ],
        validateRow: 0,
        validateColumn: 2,
      },
      {
        id: "34-10",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 20,
        given: [
          { row: 0, col: 1, value: 7 },
          { row: 0, col: 2, value: 5 },
          { row: 1, col: 0, value: 6 },
          { row: 1, col: 2, value: 6 },
          { row: 2, col: 0, value: 6 },
          { row: 2, col: 2, value: 9 },
        ],
        validateRow: 2,
        validateColumn: 0,
      },
    ],
  },
  {
    id: "set-35",
    title: "LA RECTA NUMÈRICA",
    icon: "📏",
    exercises: [
      {
        id: "35-1",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 0,
        max: 10,
        numbersToPlace: [2, 5, 8],
      },
      {
        id: "35-2",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 0,
        max: 20,
        numbersToPlace: [4, 11, 17],
      },
      {
        id: "35-3",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 5,
        max: 15,
        numbersToPlace: [6, 9, 13],
      },
      {
        id: "35-4",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 10,
        max: 20,
        numbersToPlace: [12, 15, 19],
      },
      {
        id: "35-5",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 0,
        max: 12,
        numbersToPlace: [3, 7, 11],
      },
      {
        id: "35-6",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 5,
        max: 18,
        numbersToPlace: [8, 10, 16],
      },
      {
        id: "35-7",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 2,
        max: 14,
        numbersToPlace: [4, 9, 13],
      },
      {
        id: "35-8",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 0,
        max: 20,
        numbersToPlace: [5, 14, 20],
      },
      {
        id: "35-9",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 0,
        max: 15,
        numbersToPlace: [1, 9, 14],
      },
      {
        id: "35-10",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 0,
        max: 20,
        numbersToPlace: [3, 6, 18],
      },
    ],
  },
  {
    id: "set-36",
    title: "FEM COMPRES",
    icon: "🛒",
    exercises: [
      {
        id: "36-1",
        type: "estimation",
        title: "COMPRA AMB 10€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 10€",
        money: 10,
        items: [
          { name: "PAN", price: 2, icon: "🍞" },
          { name: "LLET", price: 3, icon: "🥛" },
          { name: "OUS", price: 4, icon: "🥚" },
          { name: "POMA", price: 5, icon: "🍎" },
          { name: "FORMATGE", price: 6, icon: "🧀" },
        ],
      },
      {
        id: "36-2",
        type: "estimation",
        title: "COMPRA AMB 12€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 12€",
        money: 12,
        items: [
          { name: "LLIBRE", price: 5, icon: "📚" },
          { name: "PILOTA", price: 4, icon: "⚽" },
          { name: "COLOURS", price: 3, icon: "🖍️" },
          { name: "JOGUINA", price: 6, icon: "🧸" },
          { name: "MOTXILLA", price: 7, icon: "🎒" },
        ],
      },
      {
        id: "36-3",
        type: "estimation",
        title: "COMPRA AMB 15€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 15€",
        money: 15,
        items: [
          { name: "SABATES", price: 9, icon: "👟" },
          { name: "MITJONS", price: 3, icon: "🧦" },
          { name: "GORRA", price: 4, icon: "🧢" },
          { name: "CAMISETA", price: 6, icon: "👕" },
          { name: "PANTALONS", price: 8, icon: "👖" },
        ],
      },
      {
        id: "36-4",
        type: "estimation",
        title: "COMPRA AMB 14€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 14€",
        money: 14,
        items: [
          { name: "PIZZA", price: 7, icon: "🍕" },
          { name: "GELAT", price: 3, icon: "🍦" },
          { name: "SUC", price: 2, icon: "🥤" },
          { name: "ENTREPÀ", price: 5, icon: "🥪" },
          { name: "PASTÍS", price: 6, icon: "🍰" },
        ],
      },
      {
        id: "36-5",
        type: "estimation",
        title: "COMPRA AMB 16€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 16€",
        money: 16,
        items: [
          { name: "PLANTA", price: 6, icon: "🪴" },
          { name: "TEST", price: 4, icon: "🏺" },
          { name: "FLORS", price: 5, icon: "💐" },
          { name: "LLUM", price: 8, icon: "💡" },
          { name: "QUADRE", price: 9, icon: "🖼️" },
        ],
      },
      {
        id: "36-6",
        type: "estimation",
        title: "COMPRA AMB 18€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 18€",
        money: 18,
        items: [
          { name: "BICI", price: 10, icon: "🚲" },
          { name: "PATINET", price: 9, icon: "🛴" },
          { name: "CASC", price: 4, icon: "⛑️" },
          { name: "GUANTS", price: 3, icon: "🧤" },
          { name: "BALÓ", price: 6, icon: "🏀" },
        ],
      },
      {
        id: "36-7",
        type: "estimation",
        title: "COMPRA AMB 20€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 20€",
        money: 20,
        items: [
          { name: "CÀMERA", price: 12, icon: "📷" },
          { name: "AURICULARS", price: 8, icon: "🎧" },
          { name: "RELLOTGE", price: 7, icon: "⌚" },
          { name: "TECLAT", price: 9, icon: "⌨️" },
          { name: "RATOLÍ", price: 5, icon: "🖱️" },
        ],
      },
      {
        id: "36-8",
        type: "estimation",
        title: "COMPRA AMB 17€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 17€",
        money: 17,
        items: [
          { name: "GUITARRA", price: 11, icon: "🎸" },
          { name: "TAMBOR", price: 6, icon: "🥁" },
          { name: "TROMPETA", price: 9, icon: "🎺" },
          { name: "PIANO", price: 12, icon: "🎹" },
          { name: "VIOLÍ", price: 8, icon: "🎻" },
        ],
      },
      {
        id: "36-9",
        type: "estimation",
        title: "COMPRA AMB 19€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 19€",
        money: 19,
        items: [
          { name: "PEIXET", price: 5, icon: "🐠" },
          { name: "GATET", price: 9, icon: "🐱" },
          { name: "CONILLET", price: 7, icon: "🐰" },
          { name: "OCELL", price: 4, icon: "🐦" },
          { name: "TORTUGA", price: 6, icon: "🐢" },
        ],
      },
      {
        id: "36-10",
        type: "estimation",
        title: "COMPRA AMB 20€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 20€",
        money: 20,
        items: [
          { name: "CONSOLA", price: 13, icon: "🎮" },
          { name: "JOC", price: 7, icon: "🕹️" },
          { name: "TELÈFON", price: 15, icon: "📱" },
          { name: "TAULETA", price: 14, icon: "📲" },
          { name: "MONITOR", price: 12, icon: "🖥️" },
        ],
      },
    ],
  },
  {
    id: "set-30",
    title: "GRAELLA 1-20",
    icon: "📋",
    exercises: [
      {
        id: "30-1",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [3, 6, 9, 12, 15, 18],
        maxNumber: 20,
      },
      {
        id: "30-2",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [2, 5, 8, 11, 14, 17],
        maxNumber: 20,
      },
      {
        id: "30-3",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [1, 4, 7, 10, 13, 16, 19],
        maxNumber: 20,
      },
      {
        id: "30-4",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [2, 3, 4, 5, 6, 7],
        maxNumber: 20,
      },
      {
        id: "30-5",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [14, 15, 16, 17, 18, 19],
        maxNumber: 20,
      },
      {
        id: "30-6",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [1, 5, 6, 11, 12, 20],
        maxNumber: 20,
      },
      {
        id: "30-7",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [2, 9, 10, 13, 18, 19],
        maxNumber: 20,
      },
      {
        id: "30-8",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [3, 7, 11, 15, 20],
        maxNumber: 20,
      },
      {
        id: "30-9",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [4, 8, 12, 16],
        maxNumber: 20,
      },
      {
        id: "30-10",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [5, 10, 15, 20],
        maxNumber: 20,
      },
    ],
  },
];
