import { ExerciseSet } from "./types";

export const matematiquesExerciseSets: ExerciseSet[] = [
  {
    id: "set-21",
    title: "COMPTEM",
    icon: "🔢",
    exercises: [
      {
        id: "21-1",
        type: "number-sequence",
        title: "COMPTEM ENDAVANT",
        instructions: "ESCRIU EL NOMBRE QUE VA AL FINAL DE LA SÈRIE",
        start: 38,
        direction: "forward",
        step: 1,
        length: 5,
        missingIndices: [4],
      },
      {
        id: "21-2",
        type: "number-sequence",
        title: "COMPTEM ENRERE",
        instructions: "ESCRIU EL NOMBRE QUE VA AL PRINCIPI DE LA SÈRIE",
        start: 49,
        direction: "backward",
        step: 1,
        length: 5,
        missingIndices: [0],
      },
      {
        id: "21-3",
        type: "number-sequence",
        title: "COMPTEM DE 10 EN 10",
        instructions: "COMPLETA LES SÈRIES COMPTANT DE 10 EN 10",
        start: 10,
        direction: "forward",
        step: 10,
        length: 5,
        missingIndices: [2, 3, 4],
      },
      {
        id: "21-4",
        type: "number-sequence",
        title: "COMPTEM ENDAVANT",
        instructions: "COMPLETA LA SÈRIE",
        start: 52,
        direction: "forward",
        step: 1,
        length: 6,
        missingIndices: [2, 4],
      },
      {
        id: "21-5",
        type: "number-sequence",
        title: "COMPTEM ENRERE",
        instructions: "COMPLETA LA SÈRIE",
        start: 68,
        direction: "backward",
        step: 1,
        length: 6,
        missingIndices: [1, 3, 5],
      },
      {
        id: "21-6",
        type: "number-sequence",
        title: "COMPTEM DE 10 EN 10",
        instructions: "COMPLETA LA SÈRIE",
        start: 30,
        direction: "forward",
        step: 10,
        length: 6,
        missingIndices: [1, 3, 5],
      },
      {
        id: "21-7",
        type: "number-sequence",
        title: "COMPTEM ENDAVANT",
        instructions: "COMPLETA LA SÈRIE",
        start: 74,
        direction: "forward",
        step: 1,
        length: 7,
        missingIndices: [2, 4, 6],
      },
      {
        id: "21-8",
        type: "number-sequence",
        title: "COMPTEM ENRERE",
        instructions: "COMPLETA LA SÈRIE",
        start: 85,
        direction: "backward",
        step: 1,
        length: 7,
        missingIndices: [1, 3, 5],
      },
      {
        id: "21-9",
        type: "number-sequence",
        title: "COMPTEM DE 10 EN 10",
        instructions: "COMPLETA LA SÈRIE",
        start: 20,
        direction: "forward",
        step: 10,
        length: 7,
        missingIndices: [2, 4, 6],
      },
      {
        id: "21-10",
        type: "number-sequence",
        title: "COMPTEM DE 5 EN 5",
        instructions: "COMPLETA LA SÈRIE",
        start: 15,
        direction: "forward",
        step: 5,
        length: 8,
        missingIndices: [2, 4, 6],
      },
    ],
  },
  {
    id: "set-22",
    title: "COMPTEM",
    icon: "🏢",
    exercises: [
      {
        id: "22-1",
        type: "counting",
        title: "PINTA FINESTRES",
        instructions: "COMPTA LES FINESTRES",
        items: "🪟",
        count: 34,
        imageType: "grid",
      },
      {
        id: "22-2",
        type: "counting",
        title: "PINTA FINESTRES",
        instructions: "COMPTA LES FINESTRES",
        items: "🪟",
        count: 48,
        imageType: "grid",
      },
      {
        id: "22-3",
        type: "counting",
        title: "COMPTA EUROS",
        instructions: "COMPTA I ESCRIU QUANTS EUROS HI HA",
        items: "💶",
        count: 57,
        imageType: "groups",
      },
      {
        id: "22-4",
        type: "counting",
        title: "COMPTA OUS",
        instructions: "COMPTA QUANTS OUS HI HA",
        items: "🥚",
        count: 37,
        imageType: "grid",
      },
      {
        id: "22-5",
        type: "counting",
        title: "COMPTA QUADRADETS",
        instructions: "COMPTA QUANTS QUADRADETS PINTATS HI HA",
        items: "🟨",
        count: 42,
        imageType: "grid",
      },
      {
        id: "22-6",
        type: "counting",
        title: "COMPTA DAUS",
        instructions: "COMPTA ELS PUNTS DELS DAUS",
        items: "🎲",
        count: 73,
        imageType: "groups",
      },
      {
        id: "22-7",
        type: "counting",
        title: "COMPTA POMES",
        instructions: "COMPTA LES POMES",
        items: "🍎",
        count: 29,
        imageType: "scattered",
      },
      {
        id: "22-8",
        type: "counting",
        title: "COMPTA ESTRELLES",
        instructions: "COMPTA LES ESTRELLES",
        items: "⭐",
        count: 65,
        imageType: "groups",
      },
      {
        id: "22-9",
        type: "counting",
        title: "COMPTA FLORS",
        instructions: "COMPTA LES FLORS",
        items: "🌸",
        count: 51,
        imageType: "grid",
      },
      {
        id: "22-10",
        type: "counting",
        title: "COMPTA PILOTES",
        instructions: "COMPTA LES PILOTES",
        items: "⚽",
        count: 44,
        imageType: "scattered",
      },
      {
        id: "22-11",
        type: "counting",
        title: "COMPTA CUBS",
        instructions: "COMPTA ELS CUBS",
        items: "🧊",
        count: 38,
        imageType: "grid",
      },
      {
        id: "22-12",
        type: "counting",
        title: "COMPTA MONEDES",
        instructions: "COMPTA LES MONEDES",
        items: "🪙",
        count: 82,
        imageType: "groups",
      },
    ],
  },
  {
    id: "set-23a",
    title: "ORDENA NOMBRES",
    icon: "📊",
    exercises: [
      {
        id: "23a-1",
        type: "number-order",
        title: "PINTA EL MÉS PETIT",
        instructions: "PINTA EL NOMBRE MÉS PETIT",
        numbers: [36, 42],
        question: "smallest",
      },
      {
        id: "23a-2",
        type: "number-order",
        title: "PINTA EL MÉS GRAN",
        instructions: "PINTA EL NOMBRE MÉS GRAN",
        numbers: [49, 35],
        question: "largest",
      },
      {
        id: "23a-3",
        type: "number-order",
        title: "PINTA EL MÉS PETIT",
        instructions: "PINTA EL NOMBRE MÉS PETIT",
        numbers: [6, 45, 22],
        question: "smallest",
      },
      {
        id: "23a-4",
        type: "number-order",
        title: "PINTA EL MÉS GRAN",
        instructions: "PINTA EL NOMBRE MÉS GRAN",
        numbers: [34, 43, 33],
        question: "largest",
      },
      {
        id: "23a-5",
        type: "number-order",
        title: "PINTA EL MÉS PETIT",
        instructions: "PINTA EL NOMBRE MÉS PETIT",
        numbers: [78, 87, 71, 17],
        question: "smallest",
      },
      {
        id: "23a-6",
        type: "number-order",
        title: "PINTA EL MÉS GRAN",
        instructions: "PINTA EL NOMBRE MÉS GRAN",
        numbers: [52, 25, 55, 5],
        question: "largest",
      },
      {
        id: "23a-7",
        type: "number-order",
        title: "ORDENA DE PETIT A GRAN",
        instructions: "ORDENA ELS NOMBRES DE PETIT A GRAN",
        numbers: [30, 32, 29, 18, 27, 16],
        question: "order-asc",
      },
      {
        id: "23a-8",
        type: "number-order",
        title: "ORDENA DE GRAN A PETIT",
        instructions: "ORDENA ELS NOMBRES DE GRAN A PETIT",
        numbers: [16, 68, 15, 61, 69, 62],
        question: "order-desc",
      },
      {
        id: "23a-9",
        type: "number-order",
        title: "ORDENA DE PETIT A GRAN",
        instructions: "ORDENA ELS NOMBRES DE PETIT A GRAN",
        numbers: [5, 25, 23, 32, 3, 35],
        question: "order-asc",
      },
      {
        id: "23a-10",
        type: "number-order",
        title: "ORDENA DE GRAN A PETIT",
        instructions: "ORDENA ELS NOMBRES DE GRAN A PETIT",
        numbers: [89, 76, 58, 25, 61, 19, 42],
        question: "order-desc",
      },
      {
        id: "23a-11",
        type: "number-order",
        title: "ORDENA DE PETIT A GRAN",
        instructions: "ORDENA ELS NOMBRES DE PETIT A GRAN",
        numbers: [41, 14, 44, 11, 4],
        question: "order-asc",
      },
      {
        id: "23a-12",
        type: "number-order",
        title: "ORDENA DE GRAN A PETIT",
        instructions: "ORDENA ELS NOMBRES DE GRAN A PETIT",
        numbers: [93, 39, 99, 9, 90],
        question: "order-desc",
      },
    ],
  },
  {
    id: "set-23",
    title: "SUMEM 3 NOMBRES",
    icon: "➕",
    exercises: [
      {
        id: "23-1",
        type: "addition-three",
        title: "SUMA FORMIGUES",
        instructions: "SUMA I RESPON QUANTES FORMIGUES HI HA",
        numbers: [3, 4, 2],
        showVisual: true,
      },
      {
        id: "23-2",
        type: "addition-three",
        title: "OMPLE I SUMA",
        instructions: "OMPLE ELS BUITS I SUMA",
        numbers: [8, 2, 7],
      },
      {
        id: "23-3",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [9, 1, 6],
      },
      {
        id: "23-4",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [5, 6, 5],
      },
      {
        id: "23-5",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [3, 9, 4],
      },
      {
        id: "23-6",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [7, 5, 8],
      },
      {
        id: "23-7",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [6, 4, 9],
      },
      {
        id: "23-8",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [2, 8, 5],
      },
      {
        id: "23-9",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [4, 7, 6],
      },
      {
        id: "23-10",
        type: "addition-three",
        title: "SUMA",
        instructions: "SUMA ELS TRES NOMBRES",
        numbers: [8, 3, 7],
      },
    ],
  },
  {
    id: "set-24",
    title: "RESTEM SALTANT",
    icon: "➖",
    exercises: [
      {
        id: "24-1",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 19,
        subtract: 6,
        steps: [19, 13],
      },
      {
        id: "24-2",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 17,
        subtract: 2,
        steps: [17, 15],
      },
      {
        id: "24-3",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 16,
        subtract: 4,
        steps: [16, 12],
      },
      {
        id: "24-4",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 25,
        subtract: 8,
        steps: [25, 17],
      },
      {
        id: "24-5",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 32,
        subtract: 9,
        steps: [32, 23],
      },
      {
        id: "24-6",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 28,
        subtract: 5,
        steps: [28, 23],
      },
      {
        id: "24-7",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 41,
        subtract: 12,
        steps: [41, 29],
      },
      {
        id: "24-8",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 35,
        subtract: 7,
        steps: [35, 28],
      },
      {
        id: "24-9",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 48,
        subtract: 15,
        steps: [48, 33],
      },
      {
        id: "24-10",
        type: "subtraction-jumps",
        title: "RESTA AMB SALTS",
        instructions: "COMPLETA ELS SALTS PER RESTAR",
        start: 56,
        subtract: 18,
        steps: [56, 38],
      },
    ],
  },
  {
    id: "set-25",
    title: "SUMEM SALTANT",
    icon: "🦘",
    exercises: [
      {
        id: "25-1",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 8,
        add: 7,
        steps: [8, 10, 15],
      },
      {
        id: "25-2",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 7,
        add: 6,
        steps: [7, 10, 13],
      },
      {
        id: "25-3",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 6,
        add: 8,
        steps: [6, 10, 14],
      },
      {
        id: "25-4",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 9,
        add: 5,
        steps: [9, 10, 14],
      },
      {
        id: "25-5",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 5,
        add: 9,
        steps: [5, 10, 14],
      },
      {
        id: "25-6",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 4,
        add: 8,
        steps: [4, 10, 12],
      },
      {
        id: "25-7",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 8,
        add: 9,
        steps: [8, 10, 17],
      },
      {
        id: "25-8",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 7,
        add: 8,
        steps: [7, 10, 15],
      },
      {
        id: "25-9",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 6,
        add: 7,
        steps: [6, 10, 13],
      },
      {
        id: "25-10",
        type: "addition-jumps",
        title: "SUMA SALTANT PEL 10",
        instructions: "OMPLE ELS BUITS PER SUMAR COM SUGGEREIX EN BILLY",
        start: 9,
        add: 6,
        steps: [9, 10, 15],
      },
    ],
  },
  {
    id: "set-26",
    title: "RESTEM SALTANT PEL 10",
    icon: "⬇️",
    exercises: [
      {
        id: "26-1",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 14,
        subtract: 6,
        steps: [14, 10, 8],
      },
      {
        id: "26-2",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 13,
        subtract: 7,
        steps: [13, 10, 6],
      },
      {
        id: "26-3",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 15,
        subtract: 8,
        steps: [15, 10, 7],
      },
      {
        id: "26-4",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 12,
        subtract: 5,
        steps: [12, 10, 7],
      },
      {
        id: "26-5",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 16,
        subtract: 9,
        steps: [16, 10, 7],
      },
      {
        id: "26-6",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 17,
        subtract: 8,
        steps: [17, 10, 9],
      },
      {
        id: "26-7",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 18,
        subtract: 9,
        steps: [18, 10, 9],
      },
      {
        id: "26-8",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 11,
        subtract: 4,
        steps: [11, 10, 7],
      },
      {
        id: "26-9",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 19,
        subtract: 7,
        steps: [19, 10, 12],
      },
      {
        id: "26-10",
        type: "subtraction-jumps",
        title: "RESTA SALTANT PEL 10",
        instructions: "RESTA COM SUGGEREIX EN BILLY",
        start: 20,
        subtract: 8,
        steps: [20, 10, 12],
      },
    ],
  },
  {
    id: "set-27",
    title: "COMPTEM VAGONS",
    icon: "🚂",
    exercises: [
      {
        id: "27-1",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [2, 4, 6, 8],
        missingPositions: [4, 8],
      },
      {
        id: "27-2",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [1, 3, 5, 7, 9],
        missingPositions: [3, 7],
      },
      {
        id: "27-3",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [2, 4, 6, 8],
        missingPositions: [2, 6],
      },
      {
        id: "27-4",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 12,
        signPositions: [3, 6, 9, 12],
        missingPositions: [6, 12],
      },
      {
        id: "27-5",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [1, 4, 7, 10],
        missingPositions: [4, 10],
      },
      {
        id: "27-6",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 11,
        signPositions: [2, 5, 8, 11],
        missingPositions: [5, 11],
      },
      {
        id: "27-7",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [3, 5, 7, 9],
        missingPositions: [5, 9],
      },
      {
        id: "27-8",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 12,
        signPositions: [2, 4, 6, 8, 10],
        missingPositions: [4, 8],
      },
      {
        id: "27-9",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [2, 4, 6, 8, 10],
        missingPositions: [4, 8],
      },
      {
        id: "27-10",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 11,
        signPositions: [1, 3, 5, 7, 9],
        missingPositions: [3, 7],
      },
      {
        id: "27-11",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 10,
        signPositions: [2, 5, 8],
        missingPositions: [5, 8],
      },
      {
        id: "27-12",
        type: "train-position",
        title: "COMPLETA ELS CARTELLS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        trainLength: 12,
        signPositions: [1, 4, 7, 10],
        missingPositions: [4, 10],
      },
    ],
  },
  {
    id: "set-31",
    title: "BUSQUEM NOMBRES",
    icon: "🔍",
    exercises: [
      {
        id: "31-1",
        type: "number-pattern",
        title: "ESCRIU ELS NOMBRES QUE FALTEN",
        instructions: "COMPLETA ELS ESPAIS BLANCS",
        patterns: [
          {
            layout: "line",
            given: [
              { position: "0", value: 25 },
              { position: "1", value: 26 },
              { position: "2", value: 27 },
            ],
            missing: [],
          },
          {
            layout: "line",
            given: [{ position: "0", value: 31 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 56 }],
            missing: ["0", "1"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 35 }],
            missing: ["0", "2"],
          },
          {
            layout: "cross",
            given: [
              { position: "center", value: 59 },
              { position: "top", value: 49 },
            ],
            missing: ["left", "right", "bottom"],
          },
        ],
      },
      {
        id: "31-2",
        type: "number-pattern",
        title: "OMPLE ELS ESPAIS BLANCS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "cross",
            given: [
              { position: "left", value: 18 },
              { position: "center", value: 28 },
            ],
            missing: ["top", "right", "bottom"],
          },
          {
            layout: "cross",
            given: [
              { position: "right", value: 75 },
              { position: "center", value: 65 },
            ],
            missing: ["top", "left", "bottom"],
          },
          {
            layout: "cross",
            given: [
              { position: "center", value: 83 },
              { position: "bottom", value: 93 },
            ],
            missing: ["top", "left", "right"],
          },
          {
            layout: "cross",
            given: [
              { position: "center", value: 78 },
              { position: "right", value: 79 },
            ],
            missing: ["top", "left", "bottom"],
          },
        ],
      },
      {
        id: "31-3",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "cross",
            given: [
              { position: "center", value: 36 },
              { position: "left", value: 35 },
            ],
            missing: ["top", "right", "bottom"],
          },
          {
            layout: "cross",
            given: [
              { position: "center", value: 48 },
              { position: "top", value: 38 },
            ],
            missing: ["left", "right", "bottom"],
          },
        ],
      },
      {
        id: "31-4",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "0", value: 10 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 42 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 70 }],
            missing: ["0", "1"],
          },
        ],
      },
      {
        id: "31-5",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "cross",
            given: [
              { position: "center", value: 12 },
              { position: "bottom", value: 22 },
            ],
            missing: ["top", "left", "right"],
          },
          {
            layout: "cross",
            given: [
              { position: "center", value: 56 },
              { position: "right", value: 57 },
            ],
            missing: ["top", "left", "bottom"],
          },
        ],
      },
      {
        id: "31-6",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "cross",
            given: [
              { position: "center", value: 45 },
              { position: "left", value: 44 },
            ],
            missing: ["top", "right", "bottom"],
          },
          {
            layout: "cross",
            given: [
              { position: "center", value: 67 },
              { position: "top", value: 57 },
            ],
            missing: ["left", "right", "bottom"],
          },
        ],
      },
      {
        id: "31-7",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "0", value: 26 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 48 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 75 }],
            missing: ["0", "1"],
          },
        ],
      },
      {
        id: "31-8",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "cross",
            given: [
              { position: "center", value: 23 },
              { position: "right", value: 24 },
            ],
            missing: ["top", "left", "bottom"],
          },
          {
            layout: "cross",
            given: [
              { position: "center", value: 89 },
              { position: "bottom", value: 99 },
            ],
            missing: ["top", "left", "right"],
          },
        ],
      },
      {
        id: "31-9",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "cross",
            given: [
              { position: "center", value: 54 },
              { position: "left", value: 53 },
            ],
            missing: ["top", "right", "bottom"],
          },
          {
            layout: "cross",
            given: [
              { position: "center", value: 71 },
              { position: "top", value: 61 },
            ],
            missing: ["left", "right", "bottom"],
          },
        ],
      },
      {
        id: "31-10",
        type: "number-pattern",
        title: "COMPLETA ELS ESPAIS",
        instructions: "ESCRIU ELS NOMBRES QUE FALTEN",
        patterns: [
          {
            layout: "line",
            given: [{ position: "0", value: 1 }],
            missing: ["1", "2"],
          },
          {
            layout: "line",
            given: [{ position: "1", value: 25 }],
            missing: ["0", "2"],
          },
          {
            layout: "line",
            given: [{ position: "2", value: 37 }],
            missing: ["0", "1"],
          },
        ],
      },
    ],
  },
  {
    id: "set-34",
    title: "QUADRATS MÀGICS",
    icon: "✨",
    exercises: [
      {
        id: "34-1",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 12,
        given: [
          { row: 0, col: 0, value: 3 },
          { row: 1, col: 0, value: 4 },
          { row: 2, col: 0, value: 5 },
          { row: 2, col: 1, value: 2 },
        ],
        validateRow: 0, // Only check the top row
        validateColumn: 0, // Only check the left column
        // Solution:
        // Top row: 3 + ? + ? = 12 (any combination that sums to 9)
        // Left column: 3 + 4 + 5 = 12 ✓ (already complete)
        // Students can put any numbers as long as top row sums to 12
      },
      {
        id: "34-2",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 14,
        given: [
          { row: 0, col: 0, value: 5 },
          { row: 0, col: 2, value: 7 },
          { row: 1, col: 0, value: 2 },
          { row: 2, col: 1, value: 6 },
        ],
        validateRow: 0, // Check top row: 5 + ? + 7 = 14
        validateColumn: 2, // Check right column
      },
      {
        id: "34-3",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 15,
        given: [
          { row: 0, col: 0, value: 1 },
          { row: 1, col: 0, value: 7 },
          { row: 2, col: 0, value: 7 },
          { row: 2, col: 1, value: 4 },
          { row: 2, col: 2, value: 4 },
        ],
        // 3x3 grid with center cloud showing 15
      },
      {
        id: "34-4",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 20,
        given: [
          { row: 0, col: 0, value: 12 },
          { row: 0, col: 1, value: 2 },
          { row: 1, col: 0, value: 2 },
          { row: 2, col: 2, value: 5 },
        ],
        // 3x3 grid with center cloud showing 20
      },
      {
        id: "34-5",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 18,
        given: [
          { row: 0, col: 0, value: 9 },
          { row: 1, col: 0, value: 6 },
          { row: 2, col: 0, value: 3 },
          { row: 2, col: 1, value: 5 },
        ],
        // 3x3 grid with center cloud showing 18
      },
      {
        id: "34-6",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 16,
        given: [
          { row: 0, col: 0, value: 8 },
          { row: 0, col: 1, value: 4 },
          { row: 1, col: 2, value: 5 },
          { row: 2, col: 1, value: 7 },
        ],
        // 3x3 grid with center cloud showing 16
      },
      {
        id: "34-7",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 13,
        given: [
          { row: 0, col: 0, value: 6 },
          { row: 1, col: 0, value: 5 },
          { row: 2, col: 0, value: 2 },
          { row: 2, col: 1, value: 4 },
        ],
        // 3x3 grid with center cloud showing 13
      },
      {
        id: "34-8",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 17,
        given: [
          { row: 0, col: 0, value: 10 },
          { row: 0, col: 1, value: 3 },
          { row: 1, col: 2, value: 6 },
          { row: 2, col: 1, value: 8 },
        ],
        // 3x3 grid with center cloud showing 17
      },
      {
        id: "34-9",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 19,
        given: [
          { row: 0, col: 0, value: 11 },
          { row: 1, col: 0, value: 8 },
          { row: 2, col: 1, value: 6 },
          { row: 2, col: 2, value: 4 },
        ],
        // 3x3 grid with center cloud showing 19
      },
      {
        id: "34-10",
        type: "magic-square",
        title: "COMPLETA EL QUADRAT",
        instructions: "COMPLETA PERQUÈ LA FILA I LA COLUMNA SUMIN EL NOMBRE DEL NÚVOL",
        size: 3,
        targetSum: 21,
        given: [
          { row: 0, col: 0, value: 14 },
          { row: 0, col: 1, value: 5 },
          { row: 1, col: 2, value: 7 },
          { row: 2, col: 1, value: 9 },
        ],
        // 3x3 grid with center cloud showing 21
      },
    ],
  },
  {
    id: "set-35",
    title: "LA RECTA NUMÈRICA",
    icon: "📏",
    exercises: [
      {
        id: "35-1",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 0,
        max: 20,
        numbersToPlace: [5, 12, 18],
      },
      {
        id: "35-2",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 10,
        max: 30,
        numbersToPlace: [15, 22, 27],
      },
      {
        id: "35-3",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 20,
        max: 40,
        numbersToPlace: [25, 33, 38],
      },
      {
        id: "35-4",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 30,
        max: 50,
        numbersToPlace: [32, 41, 47],
      },
      {
        id: "35-5",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 40,
        max: 60,
        numbersToPlace: [44, 53, 59],
      },
      {
        id: "35-6",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 50,
        max: 70,
        numbersToPlace: [55, 62, 68],
      },
      {
        id: "35-7",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 60,
        max: 80,
        numbersToPlace: [63, 71, 77],
      },
      {
        id: "35-8",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 70,
        max: 90,
        numbersToPlace: [74, 82, 88],
      },
      {
        id: "35-9",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 0,
        max: 50,
        numbersToPlace: [10, 25, 40],
      },
      {
        id: "35-10",
        type: "number-line",
        title: "COL·LOCA ELS NOMBRES",
        instructions: "PINTA ELS NOMBRES A LA RECTA",
        min: 0,
        max: 100,
        numbersToPlace: [20, 50, 80],
      },
    ],
  },
  {
    id: "set-36",
    title: "FEM COMPRES",
    icon: "🛒",
    exercises: [
      {
        id: "36-1",
        type: "estimation",
        title: "COMPRA AMB 20€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 20€",
        money: 20,
        items: [
          { name: "PAN", price: 2, icon: "🍞" },
          { name: "LLET", price: 3, icon: "🥛" },
          { name: "OUS", price: 4, icon: "🥚" },
          { name: "POMA", price: 5, icon: "🍎" },
          { name: "FORMATGE", price: 6, icon: "🧀" },
        ],
      },
      {
        id: "36-2",
        type: "estimation",
        title: "COMPRA AMB 30€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 30€",
        money: 30,
        items: [
          { name: "LLIBRE", price: 8, icon: "📚" },
          { name: "PILOTA", price: 7, icon: "⚽" },
          { name: "COLOURS", price: 5, icon: "🖍️" },
          { name: "JOGUINA", price: 10, icon: "🧸" },
          { name: "MOTXILLA", price: 12, icon: "🎒" },
        ],
      },
      {
        id: "36-3",
        type: "estimation",
        title: "COMPRA AMB 25€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 25€",
        money: 25,
        items: [
          { name: "SABATES", price: 15, icon: "👟" },
          { name: "MITJONS", price: 4, icon: "🧦" },
          { name: "GORRA", price: 6, icon: "🧢" },
          { name: "CAMISETA", price: 8, icon: "👕" },
          { name: "PANTALONS", price: 12, icon: "👖" },
        ],
      },
      {
        id: "36-4",
        type: "estimation",
        title: "COMPRA AMB 40€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 40€",
        money: 40,
        items: [
          { name: "PIZZA", price: 9, icon: "🍕" },
          { name: "GELAT", price: 5, icon: "🍦" },
          { name: "SUSHI", price: 12, icon: "🍣" },
          { name: "HAMBURGUESA", price: 8, icon: "🍔" },
          { name: "PASTÍS", price: 10, icon: "🍰" },
          { name: "REFRESC", price: 3, icon: "🥤" },
        ],
      },
      {
        id: "36-5",
        type: "estimation",
        title: "COMPRA AMB 35€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 35€",
        money: 35,
        items: [
          { name: "PLANTA", price: 8, icon: "🪴" },
          { name: "TEST", price: 6, icon: "🏺" },
          { name: "FLORS", price: 7, icon: "💐" },
          { name: "LLUM", price: 12, icon: "💡" },
          { name: "QUADRE", price: 15, icon: "🖼️" },
        ],
      },
      {
        id: "36-6",
        type: "estimation",
        title: "COMPRA AMB 50€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 50€",
        money: 50,
        items: [
          { name: "BICI", price: 25, icon: "🚲" },
          { name: "PATINET", price: 20, icon: "🛴" },
          { name: "CASC", price: 10, icon: "⛑️" },
          { name: "GUANTS", price: 5, icon: "🧤" },
          { name: "MOTO", price: 30, icon: "🏍️" },
        ],
      },
      {
        id: "36-7",
        type: "estimation",
        title: "COMPRA AMB 45€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 45€",
        money: 45,
        items: [
          { name: "CÀMERA", price: 18, icon: "📷" },
          { name: "AURICULARS", price: 12, icon: "🎧" },
          { name: "RELLOTGE", price: 15, icon: "⌚" },
          { name: "TECLAT", price: 20, icon: "⌨️" },
          { name: "RATOLÍ", price: 8, icon: "🖱️" },
        ],
      },
      {
        id: "36-8",
        type: "estimation",
        title: "COMPRA AMB 60€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 60€",
        money: 60,
        items: [
          { name: "GUITARRA", price: 30, icon: "🎸" },
          { name: "TAMBOR", price: 15, icon: "🥁" },
          { name: "TROMPETA", price: 25, icon: "🎺" },
          { name: "PIANO", price: 35, icon: "🎹" },
          { name: "VIOLÍ", price: 28, icon: "🎻" },
        ],
      },
      {
        id: "36-9",
        type: "estimation",
        title: "COMPRA AMB 55€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 55€",
        money: 55,
        items: [
          { name: "PEIXET", price: 8, icon: "🐠" },
          { name: "GATET", price: 20, icon: "🐱" },
          { name: "CONILLET", price: 15, icon: "🐰" },
          { name: "OCELL", price: 12, icon: "🐦" },
          { name: "GOSSA", price: 25, icon: "🐕" },
          { name: "TORTUGA", price: 10, icon: "🐢" },
        ],
      },
      {
        id: "36-10",
        type: "estimation",
        title: "COMPRA AMB 100€",
        instructions: "CLICA ELS PRODUCTES QUE POTS COMPRAR",
        question: "COMPRA EL MÀXIM DE PRODUCTES SENSE PASSAR-TE DE 100€",
        money: 100,
        items: [
          { name: "CONSOLA", price: 40, icon: "🎮" },
          { name: "JOC", price: 25, icon: "🕹️" },
          { name: "TELÈFON", price: 50, icon: "📱" },
          { name: "TAULETA", price: 45, icon: "📲" },
          { name: "MONITOR", price: 60, icon: "🖥️" },
        ],
      },
    ],
  },
  {
    id: "set-30",
    title: "GRAELLA 1-100",
    icon: "📋",
    exercises: [
      {
        id: "30-1",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [3, 17, 22, 58, 60, 63, 71, 84, 99],
      },
      {
        id: "30-2",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [5, 12, 28, 41, 54, 67, 73, 89, 96],
      },
      {
        id: "30-3",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [7, 14, 26, 39, 52, 65, 78, 81, 94],
      },
      {
        id: "30-4",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [9, 18, 31, 44, 57, 66, 79, 88, 97],
      },
      {
        id: "30-5",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [6, 15, 24, 38, 49, 61, 72, 85, 93],
      },
      {
        id: "30-6",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [8, 19, 27, 36, 48, 59, 70, 83, 95],
      },
      {
        id: "30-7",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [4, 11, 25, 37, 46, 62, 74, 87, 98],
      },
      {
        id: "30-8",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [2, 16, 29, 43, 55, 68, 77, 86, 91],
      },
      {
        id: "30-9",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [10, 13, 33, 42, 51, 64, 75, 82, 100],
      },
      {
        id: "30-10",
        type: "grid-100",
        title: "COMPLETA LA GRAELLA",
        instructions: "COMPLETA LA GRAELLA AMB ELS NOMBRES QUE FALTEN",
        missingNumbers: [1, 20, 30, 40, 50, 69, 76, 90, 92],
      },
    ],
  },
];
